pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/gorlakishore/livestock-app.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Success') {
            steps {
                echo 'Build Successful!'
            }
        }
    }
}
