server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://database-1.cy5a4esy6mo4.us-east-1.rds.amazonaws.com:5432/livestockdb
spring.datasource.username=kishore
spring.datasource.password=Geethansh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
